#!/usr/bin/env ruby

last_ctime = nil
last_uploaded_at = nil
loop do
  current_ctime = ""
  Dir['**/'].each do |dir_name|
    current_ctime << File.stat(dir_name).ctime.to_s
  end
  if current_ctime != last_ctime
    print "\r                                                                   "
    print "\rUploading"
    $stdout.flush
    `rake load`
    last_uploaded_at = Time.now
  else
    distance_in_seconds = ((Time.now - last_uploaded_at).abs).round
    print "\rLast uploaded #{distance_in_seconds} seconds ago"
    $stdout.flush
  end
  last_ctime = current_ctime
  sleep 0.5
end
